#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app_lucky_number:
#     path: /lucky/number
#     controller: App\Controller\LuckyController::number


app_Register_hello:
    path: /Register/hello
    controller: App\Controller\Register::hello
    

app_edit_cuenta:
    path: /EditarCuentaController/edit
    controller: App\Controller\EditarCuentaController::edit

